definitions:
  model.Artist:
    properties:
      description:
        type: string
      id:
        example: 3983a1d6-759b-4e5e-b307-7b7e06a05a85
        type: string
      name:
        type: string
    type: object
  model.Track:
    properties:
      artistID:
        items:
          type: string
        type: array
      id:
        type: string
      length:
        type: integer
      name:
        type: string
    type: object
host: localhost:4040
info:
  contact: {}
  description: Spotify API clone
  title: Swagger Flotify API
  version: "1.0"
paths:
  /artist:
    post:
      consumes:
      - application/json
      description: Create a new artist
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Artist'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create an artist
      tags:
      - artist
  /track:
    post:
      consumes:
      - application/json
      description: Create a new track
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Track'
        "400":
          description: Bad request
      summary: Create a track
      tags:
      - track
  /track/{id}:
    get:
      description: Get track's information by its ID
      parameters:
      - description: Track ID
        example: '"3983a1d6-759b-4e5e-b307-7b7e06a05a85"'
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Track'
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Get track's information
      tags:
      - track
swagger: "2.0"
